version: "3"
services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=shareService
      - POSTGRES_DB=shareService
      - POSTGRES_PASSWORD=12345S
  api:
    build: ./api
    ports:
      - "80:80"
    environment:
      - PORT=80
    depends_on:
      - db